##
# Stampede
-
  name:  'Stampede-SvgSprite'
  uriPattern: 'stampede/svgsprite'
  defaults:
    '@package':    'Sitegeist.Stampede'
    '@controller': 'Svg'
    '@action':     'sprite'
  httpMethods: ['GET']
  appendExceedingArguments: TRUE
