Sitegeist:
  Stampede:
    collections: []
      # example: resource://Vendor.Site/Private/Icons

  Silhouettes:
    properties:
      stampede:
        icon:
          type: string
          defaultValue: ''
          ui:
            reloadIfChanged: true
            label: 'Icon'
            inspector:
              group: icon
              editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                dataSourceIdentifier: 'sitegeist-stampede-icons'
                dataSourceAdditionalData:
                  collections: ['foo', 'bar']
Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.Stampede: true
  Fusion:
    defaultContext:
      Stampede: Sitegeist\Stampede\Eel\IconHelper
  Flow:
    mvc:
      routes:
        'Sitegeist.Stampede':
          position: 'before Neos.Neos'

