Sitegeist:
  Stampede:
    iconSets:
      sitegeistde: resource://Sitegeist.SitegeistDe/Private/Icons

Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.Stampede: true
  Fusion:
    defaultContext:
      Stampede: Sitegeist\Stampede\Eel\IconHelper
  Flow:
    mvc:
      routes:
        'Sitegeist.Stampede':
          position: 'before Neos.Neos'

